import { Inter } from 'next/font/google'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  if (process.env.NODE_ENV === 'development') {
    ;(async () => {
      const { worker } = await import('../mocks/broswer')
      worker.start()
    })()
  }

  return (
    <html lang="ko">
      <body className={inter.className}>
        <h1>Study</h1>
        <div>{children}</div>
      </body>
    </html>
  )
}
